{% set name = "SRC-Endpoints" %}
{% set version = "0.0.0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/SRC_Endpoints-{{ version }}.tar.gz
  sha256: a04456bf1c91e4948ab7b537ea985799dcbe94cb97c12f47236c71d9d54c9ac2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - pandas
    - requests

test:
  imports:
    - SRC_Endpoints
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/SRC-Endpoints
  summary: A higher level of abstraction around API Endpoints.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JohanMabille
